### PR TITLE
Revival branch

### PR DESCRIPTION
**Pull request by Xinnx**
- [x] Removed Terms of Use agreement as this project isn't Arcemu anymore
- [x] Added PR-384 'MySQL SSL and Compression support' from @Artox
- [x] Added PR-385 'Fix Compile warning...' from @Artox
- [ ] Added PR-386 'ARM Support' from @Artox [Removed until a later date]
- [x] Added PR-406 'Talent inspect buffer patch' from @Thetruecrow
- [x] Added PR-407 'Mount scaling patch' from @Thetruecrow
- [x] Added PR-408 'Fixed action buttons...' from @Thetruecrow

I would like to continue merging pull requests from the main Arcemu repo such as

- [ ] PR-246
- [ ] PR-260
- [ ] PR-357
- [ ] PR-392

But some of these patches have had the sources removed or branches deleted.
I also plan on removing Windows support at a later time because I have no interest in maintaining it.
but that will be included in a separate branch & possibly a milestone.

Also to Artox and Thetruecrow, I mentioned you because the source is your source code. If you have issues merging them into arcemu-ng just tell me and I will promptly remove the patches. I will also be leaving this PR open for a while to wait for responses.

> Arcemu is dead; long live arcemu!

### CODE REVIEW

**Comment by Artox** [comment]
I am fine with you taking my code.
However I would like to note that the arm patch is not complete. There are a few places with room for improvement. Might I suggest having a seperate pull-request for that one?

Just one example is my unconditional use of the gcc atomic functions. These should be gated by preprocessor checks for gcc, and its version, and there should be a fallback error pragma to notify users when they are trying to use some other compiler.

**Comment by Artox** [comment]
just another comment: is windows so hard to maintain? I suspect it should be easy enough to deal with.

**Comment by Artox** [comment]
and another one ....
Might I suggest keeping the full history when merging pull request? You just condensed it all into a single commit. Chances are the authors were writing commit messages on purpose ....

**Comment by Xinnx** [comment]
I did not have access to the original pull requests without messing with github. In the future I agree that it would be better to keep all the commits but I had to individually pull a .patch for each PR from the original arcemu PR page and then do a `git apply` and then commit the changes in my working branch.

**Comment by Artox** [comment]
git am is able to apply a .patch file with commit message. But I do understand the difficulty.

**Pull request merged**
